### ISSUE TITLE
write new import_script 

### ISSUE THREAD

**Issue by csae8092** [acdh-oeaw/daacda-go-digital#9]
based upon 0_Database List_2018 06 04.xlsx
not very high priority but nice to have

**Comment by aureon249** [comment]
--settings=daacda.settings.play

**Comment by aureon249** [comment]
first running draft available (on gitignore)

**Comment by csae8092** [comment]
done with comits https://github.com/acdh-oeaw/daacda-go-digital/commit/677f0f7938d93831700c144a3e5e9665a55db0b0 ff
